# Generated by Django 6.0.4 on 2026-05-22 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetinopathySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_identifier", models.CharField(db_index=True, max_length=50)),
                (
                    "initials",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subject initials as sent by the camera.",
                        max_length=10,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sex as sent by the camera.",
                        max_length=10,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        help_text="Age in years as sent by the camera.",
                        null=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier for the camera device.",
                        max_length=100,
                    ),
                ),
                (
                    "site_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Study site identifier.",
                        max_length=50,
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Retinopathy Session",
                "verbose_name_plural": "Retinopathy Sessions",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="RetinalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("left", "Left eye"),
                            ("right", "Right eye"),
                            ("report", "Report"),
                        ],
                        help_text="Category of this file: left eye, right eye, or report.",
                        max_length=10,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename as sent by the camera software.",
                        max_length=255,
                    ),
                ),
                (
                    "stored_filename",
                    models.CharField(
                        help_text="UUID-based filename used on disk.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MIME type of the uploaded file (e.g. image/jpeg, application/pdf).",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hex digest of the stored file.",
                        max_length=64,
                    ),
                ),
                (
                    "capture_datetime",
                    models.DateTimeField(
                        help_text="Capture timestamp as reported by the camera."
                    ),
                ),
                ("received_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="edc_retinopathy.retinopathysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retinal Image",
                "verbose_name_plural": "Retinal Images",
                "ordering": ["-received_datetime"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "file_type"), name="unique_session_file_type"
                    )
                ],
            },
        ),
    ]
