# Generated by Django 6.0.4 on 2026-05-29 03:18

import _socket
import uuid

import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_prn.prn_model_manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sessionfile",
            managers=[
                ("objects", edc_prn.prn_model_manager.PrnModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSessionFile",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("left", "Left eye"),
                            ("right", "Right eye"),
                            ("left_report", "Left eye report"),
                            ("right_report", "Right eye report"),
                            ("report", "Report"),
                        ],
                        help_text="Category: left eye, right eye, left/right report, or combined report.",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename as sent by the camera software.",
                        max_length=255,
                    ),
                ),
                (
                    "stored_filename",
                    models.CharField(
                        db_index=True,
                        help_text="UUID-based filename used on disk.",
                        max_length=255,
                    ),
                ),
                (
                    "file_content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image/jpeg", "JPEG image"),
                            ("image/png", "PNG image"),
                            ("application/pdf", "PDF document"),
                            ("text/html", "HTML document"),
                        ],
                        default="",
                        help_text="MIME type of the uploaded file.",
                        max_length=100,
                        verbose_name="content type",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes.",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hex digest of the stored file.",
                        max_length=64,
                    ),
                ),
                (
                    "capture_datetime",
                    models.DateTimeField(
                        help_text="Capture timestamp as reported by the camera.",
                    ),
                ),
                ("received_datetime", models.DateTimeField(blank=True, editable=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_retinopathy.camerasession",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Session file",
                "verbose_name_plural": "historical Session files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
