# Generated by Django 6.0.4 on 2026-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0002_alter_sessionfile_managers_historicalsessionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasession",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("combined", "Combined (one report for both eyes)"),
                    ("per_eye", "Per eye (one report per eye)"),
                ],
                default="combined",
                help_text="Combined: one report for both eyes. Per eye: one report per eye.",
                max_length=25,
                verbose_name="Report type",
            ),
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("combined", "Combined (one report for both eyes)"),
                    ("per_eye", "Per eye (one report per eye)"),
                ],
                default="combined",
                help_text="Combined: one report for both eyes. Per eye: one report per eye.",
                max_length=25,
                verbose_name="Report type",
            ),
        ),
    ]
