# Generated by Django 6.0.5 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0003_camerasession_report_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionfile",
            name="unique_session_orig_filename",
        ),
        migrations.RenameField(
            model_name="historicalsessionfile",
            old_name="session",
            new_name="camera_session",
        ),
        migrations.RenameField(
            model_name="sessionfile",
            old_name="session",
            new_name="camera_session",
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("combined", "Combined (one report for both eyes)"),
                    ("per_eye", "Per eye (one report per eye)"),
                ],
                default="combined",
                max_length=25,
                verbose_name="Report type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("combined", "Combined (one report for both eyes)"),
                    ("per_eye", "Per eye (one report per eye)"),
                ],
                default="combined",
                max_length=25,
                verbose_name="Report type",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionfile",
            constraint=models.UniqueConstraint(
                fields=("camera_session", "original_filename"),
                name="unique_session_orig_filename",
            ),
        ),
    ]
