# Generated by Django 6.0.5 on 2026-06-04 22:16

import _socket
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_crypto_fields.fields.encrypted_char_field
import django_revision.revision_field
import edc_model_fields.fields.other_charfield
import edc_prn.prn_model_manager
import edc_sites.managers
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_retinopathy",
            "0004_remove_sessionfile_unique_session_orig_filename_and_more",
        ),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasession",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If referred, may we contact the patient to followup on the referral?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camerasession",
            name="op_comment",
            field=models.TextField(default="", verbose_name="Opthamologist's comment"),
        ),
        migrations.AddField(
            model_name="camerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Opthamologist referred the subject for follow-up care?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camerasession",
            name="referred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="If referred, date of referral"
            ),
        ),
        migrations.AddField(
            model_name="camerasession",
            name="referred_to",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="If referred, name of facility subject referred",
            ),
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If referred, may we contact the patient to followup on the referral?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="op_comment",
            field=models.TextField(default="", verbose_name="Opthamologist's comment"),
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Opthamologist referred the subject for follow-up care?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="referred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="If referred, date of referral"
            ),
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="referred_to",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="If referred, name of facility subject referred",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="pregnant",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Not applicable for male patients.",
                max_length=25,
                verbose_name="Is the patient pregnant?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="pregnant",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Not applicable for male patients.",
                max_length=25,
                verbose_name="Is the patient pregnant?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsessionfile",
            name="file_content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image/jpeg", "JPEG image"),
                    ("image/png", "PNG image"),
                    ("application/pdf", "PDF document"),
                    ("application/dicom", "DICOM file"),
                    ("text/html", "HTML document"),
                ],
                default="",
                help_text="MIME type of the uploaded file.",
                max_length=100,
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsessionfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("left", "Left eye"),
                    ("right", "Right eye"),
                    ("left_dicom", "Left eye DICOM"),
                    ("right_dicom", "Right eye DICOM"),
                    ("left_report", "Left eye report"),
                    ("right_report", "Right eye report"),
                    ("report", "Report"),
                ],
                help_text="Category: left eye, right eye, left/right report, or combined report.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="file_content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image/jpeg", "JPEG image"),
                    ("image/png", "PNG image"),
                    ("application/pdf", "PDF document"),
                    ("application/dicom", "DICOM file"),
                    ("text/html", "HTML document"),
                ],
                default="",
                help_text="MIME type of the uploaded file.",
                max_length=100,
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("left", "Left eye"),
                    ("right", "Right eye"),
                    ("left_dicom", "Left eye DICOM"),
                    ("right_dicom", "Right eye DICOM"),
                    ("left_report", "Left eye report"),
                    ("right_report", "Right eye report"),
                    ("report", "Report"),
                ],
                help_text="Category: left eye, right eye, left/right report, or combined report.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContactAttempt",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_identifier",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                (
                    "initials",
                    django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                        blank=True,
                        editable=False,
                        help_text=" (Encryption: RSA local)",
                        max_length=71,
                        null=True,
                    ),
                ),
                ("age_in_years", models.IntegerField(editable=False, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        editable=False,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "number_of_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "contact_made",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Were you able to speak with the subject or their representative?",
                    ),
                ),
                (
                    "agreed_to_attend",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="If contact made, has the subject agreed to attend the exam?",
                    ),
                ),
                (
                    "agreed_to_attend_datetime",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date the subject plans to attend the exam?",
                    ),
                ),
                (
                    "declined_reason",
                    models.TextField(
                        default="",
                        verbose_name="If the subject declined, give a brief reason why",
                    ),
                ),
                (
                    "registered_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_attempt",
                        to="edc_retinopathy.registeredsubjectproxy",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Attempt",
                "verbose_name_plural": "Contact Attempts",
            },
            managers=[
                ("objects", edc_prn.prn_model_manager.PrnModelManager()),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalContactAttempt",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "subject_identifier",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                (
                    "initials",
                    django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                        blank=True,
                        editable=False,
                        help_text=" (Encryption: RSA local)",
                        max_length=71,
                        null=True,
                    ),
                ),
                ("age_in_years", models.IntegerField(editable=False, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        editable=False,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "number_of_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "contact_made",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Were you able to speak with the subject or their representative?",
                    ),
                ),
                (
                    "agreed_to_attend",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="If contact made, has the subject agreed to attend the exam?",
                    ),
                ),
                (
                    "agreed_to_attend_datetime",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date the subject plans to attend the exam?",
                    ),
                ),
                (
                    "declined_reason",
                    models.TextField(
                        default="",
                        verbose_name="If the subject declined, give a brief reason why",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_retinopathy.registeredsubjectproxy",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contact Attempt",
                "verbose_name_plural": "historical Contact Attempts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReferralFollowup",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "subject_identifier",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                (
                    "initials",
                    django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                        blank=True,
                        editable=False,
                        help_text=" (Encryption: RSA local)",
                        max_length=71,
                        null=True,
                    ),
                ),
                ("age_in_years", models.IntegerField(editable=False, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        editable=False,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attended",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=25,
                        verbose_name="Did you attend the health facility following referral from the META Trial",
                    ),
                ),
                (
                    "other_missed_referral_reason",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        max_length=35,
                        null=True,
                        verbose_name="If other 'reason for not seeking further care', please specify ...",
                    ),
                ),
                (
                    "facility_attended",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="If 'Yes', please give the name of the facility you attended",
                    ),
                ),
                (
                    "attended_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="What was the date you attended the health facility named above?",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_subject",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_retinopathy.registeredsubjectproxy",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Follow-up after referral",
                "verbose_name_plural": "historical Follow-up after referral",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MissedReferralReasons",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="This is the stored value, required",
                        max_length=250,
                        unique=True,
                        verbose_name="Stored value",
                    ),
                ),
                (
                    "plural_name",
                    models.CharField(
                        default="", max_length=250, verbose_name="Plural name"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="(suggest 40 characters max.)",
                        max_length=250,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "display_index",
                    models.IntegerField(
                        default=0,
                        help_text="Index to control display order if not alphabetical, not required",
                        verbose_name="display index",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Not required",
                        max_length=25,
                    ),
                ),
                ("extra_value", models.CharField(default="", max_length=250)),
                (
                    "version",
                    models.CharField(default="1.0", editable=False, max_length=35),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Missed Referral Reasons",
                "verbose_name_plural": "Missed Referral Reasons",
                "ordering": ("display_index", "display_name"),
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "indexes": [
                    models.Index(
                        fields=["display_index", "display_name"],
                        name="edc_retinop_display_46ce13_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralFollowup",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_identifier",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                (
                    "initials",
                    django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                        blank=True,
                        editable=False,
                        help_text=" (Encryption: RSA local)",
                        max_length=71,
                        null=True,
                    ),
                ),
                ("age_in_years", models.IntegerField(editable=False, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        editable=False,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attended",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=25,
                        verbose_name="Did you attend the health facility following referral from the META Trial",
                    ),
                ),
                (
                    "other_missed_referral_reason",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        max_length=35,
                        null=True,
                        verbose_name="If other 'reason for not seeking further care', please specify ...",
                    ),
                ),
                (
                    "facility_attended",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="If 'Yes', please give the name of the facility you attended",
                    ),
                ),
                (
                    "attended_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="What was the date you attended the health facility named above?",
                    ),
                ),
                (
                    "missed_referral_reasons",
                    models.ManyToManyField(
                        blank=True,
                        to="edc_retinopathy.missedreferralreasons",
                        verbose_name="If 'No', please provide a reason for not seeking further care or follow up?",
                    ),
                ),
                (
                    "registered_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral_followup",
                        to="edc_retinopathy.registeredsubjectproxy",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow-up after referral",
                "verbose_name_plural": "Follow-up after referral",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["modified", "created"],
                        name="edc_retinop_modifie_2aa8de_idx",
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="edc_retinop_user_mo_6aa8b4_idx",
                    ),
                ],
            },
            managers=[
                ("objects", edc_prn.prn_model_manager.PrnModelManager()),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
