# Generated by Django 6.0.5 on 2026-06-04 23:25

import _socket
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_retinopathy",
            "0005_camerasession_may_contact_camerasession_op_comment_and_more",
        ),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmRetinopathyScreening",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "od_hemorrhages",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MILD", "Mild (< 20 overall)"),
                            ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                            ("Not evaluated", "Not Evaluated"),
                        ],
                        default="NONE",
                        max_length=25,
                        verbose_name="OD Microaneurysms / Hemorrhages",
                    ),
                ),
                (
                    "od_cotton_wool_spots",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD Cotton Wool Spots",
                    ),
                ),
                (
                    "od_irma_venous_beading",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD IRMA / Venous Beading",
                    ),
                ),
                (
                    "od_neovascularization",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD Neovascularization / Vitreous Hemorrhage",
                    ),
                ),
                (
                    "od_macular_involvement",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        help_text="Hard lipid exudates or hemorrhages within 1 disc diameter of foveal center",
                        max_length=20,
                        verbose_name="OD Macular Involvement",
                    ),
                ),
                (
                    "os_hemorrhages",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MILD", "Mild (< 20 overall)"),
                            ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                            ("Not evaluated", "Not Evaluated"),
                        ],
                        default="NONE",
                        max_length=25,
                        verbose_name="OD Microaneurysms / Hemorrhages",
                    ),
                ),
                (
                    "os_cotton_wool_spots",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD Cotton Wool Spots",
                    ),
                ),
                (
                    "os_irma_venous_beading",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD IRMA / Venous Beading",
                    ),
                ),
                (
                    "os_neovascularization",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="OD Neovascularization / Vitreous Hemorrhage",
                    ),
                ),
                (
                    "os_macular_involvement",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        help_text="Hard lipid exudates or hemorrhages within 1 disc diameter of foveal center",
                        max_length=20,
                        verbose_name="OD Macular Involvement",
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "interpreted_by",
                    models.CharField(
                        help_text="Name or ID of the reading Ophthalmologist",
                        max_length=150,
                    ),
                ),
                (
                    "image_quality",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent / Clear Media"),
                            ("ACCESSIBLE", "Acceptable for Diagnostic Evaluation"),
                            ("UNGRADABLE", "Ungradable / Insufficient Quality"),
                            ("Not evaluated", "Not Evaluated"),
                        ],
                        default="ACCESSIBLE",
                        max_length=20,
                    ),
                ),
                (
                    "limitation_cataract",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="Cataract / Media Opacity",
                    ),
                ),
                (
                    "limitation_small_pupil",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="Poor Dilation / Small Pupil",
                    ),
                ),
                (
                    "limitation_artifact",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="Artifact (Blink, dust, glare)",
                    ),
                ),
                (
                    "limitation_blur",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        max_length=20,
                        verbose_name="Motion Blur / Poor Focus",
                    ),
                ),
                (
                    "final_severity_grade",
                    models.CharField(
                        choices=[
                            ("NONE", "No Retinopathy"),
                            (
                                "MILD_NPDR",
                                "Mild Non-Proliferative DR (Microaneurysms only)",
                            ),
                            ("MODERATE_NPDR", "Moderate Non-Proliferative DR"),
                            (
                                "SEVERE_NPDR",
                                "Severe Non-Proliferative DR (Meets 4-2-1 Rule)",
                            ),
                            (
                                "PDR",
                                "Proliferative Diabetic Retinopathy (Neovascularization)",
                            ),
                            ("UNGRADABLE", "Ungradable"),
                            ("Not evaluated", "Not Evaluated"),
                        ],
                        help_text="Overall classification based on the worst-performing eye",
                        max_length=20,
                    ),
                ),
                (
                    "dme_suspected",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("not_evaluated", "Not evaluated"),
                        ],
                        help_text="Automatically flagged Yes if macular involvement is checked in either eye",
                        max_length=20,
                        verbose_name="Diabetic Macular Edema Suspected",
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine Rescreen in 12 Months"),
                            ("EARLY", "Early Rescreen in 6 Months"),
                            ("REFERRAL", "Referral to Retina Specialist"),
                            ("RETAKE", "Recall Patient for Re-imaging"),
                            ("Not evaluated", "Not Evaluated"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional diagnostic narrative annotations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diabetic Retinopathy Screening",
                "verbose_name_plural": "Diabetic Retinopathy Screenings",
                "ordering": ("-report_datetime",),
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "default_manager_name": "objects",
            },
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="contactattempt",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Contact Attempt",
                "verbose_name_plural": "Contact Attempts",
            },
        ),
        migrations.AddIndex(
            model_name="contactattempt",
            index=models.Index(
                fields=["modified", "created"], name="edc_retinop_modifie_5515ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactattempt",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_retinop_user_mo_c26ec4_idx",
            ),
        ),
        migrations.AddField(
            model_name="dmretinopathyscreening",
            name="camera_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_retinopathy.camerasession",
            ),
        ),
        migrations.AddField(
            model_name="dmretinopathyscreening",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddIndex(
            model_name="dmretinopathyscreening",
            index=models.Index(
                fields=["modified", "created"], name="edc_retinop_modifie_7cc782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmretinopathyscreening",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_retinop_user_mo_22c7a7_idx",
            ),
        ),
    ]
