# Generated by Django 6.0.5 on 2026-06-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_retinopathy",
            "0006_dmretinopathyscreening_alter_contactattempt_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="camera_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_retinopathy.camerasession",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_cotton_wool_spots",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                max_length=20,
                verbose_name="OS Cotton Wool Spots",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_hemorrhages",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILD", "Mild (< 20 overall)"),
                    ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                    ("Not evaluated", "Not Evaluated"),
                ],
                default="NONE",
                max_length=25,
                verbose_name="OS Microaneurysms / Hemorrhages",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_irma_venous_beading",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                max_length=20,
                verbose_name="OS IRMA / Venous Beading",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_macular_involvement",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Hard lipid exudates or hemorrhages within 1 disc diameter of foveal center",
                max_length=20,
                verbose_name="OS Macular Involvement",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_neovascularization",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                max_length=20,
                verbose_name="OS Neovascularization / Vitreous Hemorrhage",
            ),
        ),
    ]
