# Generated by Django 6.0.5 on 2026-06-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0008_alter_dmretinopathyscreening_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattempt",
            name="agreed_to_attend",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="If contact made, has the subject agreed to attend the exam?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontactattempt",
            name="agreed_to_attend",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="If contact made, has the subject agreed to attend the exam?",
            ),
        ),
    ]
