# Generated by Django 6.0.5 on 2026-06-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0009_alter_contactattempt_agreed_to_attend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattempt",
            name="declined_reason",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="If the subject declined, give a brief reason why",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontactattempt",
            name="declined_reason",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="If the subject declined, give a brief reason why",
            ),
        ),
    ]
