# Generated by Django 6.0.5 on 2026-06-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0010_alter_contactattempt_declined_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattempt",
            name="registered_subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_attempt",
                to="edc_retinopathy.registeredsubjectproxy",
            ),
        ),
    ]
