# Generated by Django 6.0.5 on 2026-06-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0011_alter_contactattempt_registered_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactattempt",
            old_name="agreed_to_attend_datetime",
            new_name="agreed_to_attend_date",
        ),
        migrations.RenameField(
            model_name="historicalcontactattempt",
            old_name="agreed_to_attend_datetime",
            new_name="agreed_to_attend_date",
        ),
        migrations.AlterField(
            model_name="contactattempt",
            name="agreed_to_attend",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If contact made, has the subject agreed to attend the exam?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontactattempt",
            name="agreed_to_attend",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If contact made, has the subject agreed to attend the exam?",
            ),
        ),
    ]
