# Generated by Django 6.0.5 on 2026-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_retinopathy",
            "0012_rename_agreed_to_attend_datetime_contactattempt_agreed_to_attend_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasession",
            name="self_reported_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported",
                max_length=15,
                verbose_name="Has the subject reported any issue with their eyes making them ineligible for retinopathy screening",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcamerasession",
            name="self_reported_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported",
                max_length=15,
                verbose_name="Has the subject reported any issue with their eyes making them ineligible for retinopathy screening",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If referred, may we contact the patient to followup on the referral?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Opthamologist referred the subject for follow-up care?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="may_contact",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If referred, may we contact the patient to followup on the referral?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Opthamologist referred the subject for follow-up care?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
    ]
