# Generated by Django 6.0.5 on 2026-06-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0013_camerasession_self_reported_impairment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmretinopathyscreening",
            name="subject_identifier",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicaldmretinopathyscreening",
            name="subject_identifier",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
