# Generated by Django 6.0.5 on 2026-06-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0014_dmretinopathyscreening_subject_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camerasession",
            name="op_comment",
            field=models.TextField(
                default="", verbose_name="Ophthalmologist's comment"
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Ophthalmologist referred the subject for follow-up care?",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="od_hemorrhages",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILD", "Mild (< 20 overall)"),
                    ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                    ("Not evaluated", "Not Evaluated"),
                ],
                max_length=25,
                verbose_name="OD Microaneurysms / Hemorrhages",
            ),
        ),
        migrations.AlterField(
            model_name="dmretinopathyscreening",
            name="os_hemorrhages",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILD", "Mild (< 20 overall)"),
                    ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                    ("Not evaluated", "Not Evaluated"),
                ],
                max_length=25,
                verbose_name="OS Microaneurysms / Hemorrhages",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="op_comment",
            field=models.TextField(
                default="", verbose_name="Ophthalmologist's comment"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="op_referral",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Has the Ophthalmologist referred the subject for follow-up care?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmretinopathyscreening",
            name="od_hemorrhages",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILD", "Mild (< 20 overall)"),
                    ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                    ("Not evaluated", "Not Evaluated"),
                ],
                max_length=25,
                verbose_name="OD Microaneurysms / Hemorrhages",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmretinopathyscreening",
            name="os_hemorrhages",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILD", "Mild (< 20 overall)"),
                    ("SEVERE", "Severe (>= 20 in at least one quadrant)"),
                    ("Not evaluated", "Not Evaluated"),
                ],
                max_length=25,
                verbose_name="OS Microaneurysms / Hemorrhages",
            ),
        ),
    ]
