# Generated by Django 6.0.6 on 2026-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0015_alter_camerasession_op_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsessionfile",
            name="preview_filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="JPEG preview filename for DICOM files (relative to images/).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sessionfile",
            name="preview_filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="JPEG preview filename for DICOM files (relative to images/).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="self_reported_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported",
                max_length=25,
                verbose_name="Has the subject reported any issue with their eyes making them ineligible for retinopathy screening",
            ),
        ),
        migrations.AlterField(
            model_name="camerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="ocular_interventions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Including retinal laser treatment, intravitreal injections, or intraocular surgeries (excluding uncomplicated cataract surgery).",
                max_length=25,
                verbose_name="Does the patient have a history of ocular interventions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="photosensitive",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="Is the patient photosensitive or otherwise contraindicated for retinal imaging?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="retinal_conditions",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Such as macular edema, retinal vascular occlusion, or any form of retinopathy not related to diabetes.",
                max_length=25,
                verbose_name="Does the patient have pre-existing retinal conditions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="self_reported_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported",
                max_length=25,
                verbose_name="Has the subject reported any issue with their eyes making them ineligible for retinopathy screening",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcamerasession",
            name="visual_impairment",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                help_text="Self-reported or diagnosed.",
                max_length=25,
                verbose_name="Does the patient have persistent visual impairment in one or both eyes?",
            ),
        ),
    ]
