# Generated by Django 6.0.8 on 2026-08-07 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0016_historicalsessionfile_preview_filename_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CameraSession",
            new_name="EyeExamRegister",
        ),
        migrations.RenameModel(
            old_name="HistoricalCameraSession",
            new_name="HistoricalEyeExamRegister",
        ),
        migrations.AlterModelOptions(
            name="eyeexamregister",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Eye exam register",
                "verbose_name_plural": "Eye exam register",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaleyeexamregister",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Eye exam register",
                "verbose_name_plural": "historical Eye exam register",
            },
        ),
        migrations.RemoveConstraint(
            model_name="sessionfile",
            name="unique_session_orig_filename",
        ),
        migrations.RenameField(
            model_name="dmretinopathyscreening",
            old_name="camera_session",
            new_name="eye_exam_register",
        ),
        migrations.RenameField(
            model_name="historicaldmretinopathyscreening",
            old_name="camera_session",
            new_name="eye_exam_register",
        ),
        migrations.RenameField(
            model_name="historicalsessionfile",
            old_name="camera_session",
            new_name="eye_exam_register",
        ),
        migrations.RenameField(
            model_name="sessionfile",
            old_name="camera_session",
            new_name="eye_exam_register",
        ),
        migrations.RenameIndex(
            model_name="eyeexamregister",
            new_name="edc_retinop_modifie_f9d460_idx",
            old_name="edc_retinop_modifie_085461_idx",
        ),
        migrations.RenameIndex(
            model_name="eyeexamregister",
            new_name="edc_retinop_user_mo_02d2e1_idx",
            old_name="edc_retinop_user_mo_92e1e0_idx",
        ),
        migrations.AddConstraint(
            model_name="sessionfile",
            constraint=models.UniqueConstraint(
                fields=("eye_exam_register", "original_filename"),
                name="unique_session_orig_filename",
            ),
        ),
    ]
