# Generated by Django 6.0.8 on 2026-08-12 17:39

import _socket
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_crypto_fields.fields.encrypted_char_field
import django_revision.revision_field
import edc_prn.prn_model_manager
import edc_sites.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0017_rename_camerasession_eyeexamregister_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactAttempt",
            new_name="CallList",
        ),
        migrations.RenameModel(
            old_name="HistoricalContactAttempt",
            new_name="HistoricalCallList",
        ),
    ]
