# Generated by Django 6.0.8 on 2026-08-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_retinopathy", "0018_calllist_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="calllist",
            new_name="edc_retinop_modifie_061366_idx",
            old_name="edc_retinop_modifie_5515ec_idx",
        ),
        migrations.RenameIndex(
            model_name="calllist",
            new_name="edc_retinop_user_mo_b1bdba_idx",
            old_name="edc_retinop_user_mo_c26ec4_idx",
        ),
        migrations.AlterField(
            model_name="calllist",
            name="registered_subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="call_list",
                to="edc_retinopathy.registeredsubjectproxy",
            ),
        ),
    ]
