LEFT_EYE = "left"
RIGHT_EYE = "right"
LEFT_DICOM = "left_dicom"
RIGHT_DICOM = "right_dicom"
LEFT_REPORT = "left_report"
RIGHT_REPORT = "right_report"
REPORT = "report"

REPORT_TYPE_COMBINED = "combined"
REPORT_TYPE_PER_EYE = "per_eye"

IMAGE_JPEG = "image/jpeg"
IMAGE_PNG = "image/png"
APPLICATION_PDF = "application/pdf"
APPLICATION_DICOM = "application/dicom"
TEXT_HTML = "text/html"
