# Generated by Django 6.0.5 on 2026-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisteredSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=50, unique=True)),
                ("initials", models.CharField(blank=True, default="", max_length=10)),
                ("gender", models.CharField(blank=True, default="", max_length=1)),
                ("dob", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
